import  express  from "express";
import * as shoppingCartControllers from '../controllers/ShoppingCart.js';
import * as auth from '../controllers/auth.js';
const router=express.Router();
router.get("/",auth.simpleAuth,shoppingCartControllers.getAllShoppingCart);
router.post("/",auth.simpleAuth,shoppingCartControllers.addNewItemToShoppingCart);
router.delete("/:id",auth.simpleAuth,shoppingCartControllers.deleteItemFromShoppingCart);
router.put("/:id",auth.simpleAuth,shoppingCartControllers.updateAmountItemInShoppingCart);
router.put("/update/:id",auth.adminAuth,shoppingCartControllers.updateItemsInShoppingCart);
router.put("/changeIsSelectedProduct/:id",auth.simpleAuth,shoppingCartControllers.changeIsSelectedProduct);
export default router;
